name: label1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [10.15, 16.15.1 , 18.4.0]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-verison}}
      - name: Use node
        run: |
          node --version

    
